# Use the lightweight Alpine version of Redis
FROM redis:7.2-alpine

# Copy your custom config into the container
COPY redis.conf /usr/local/etc/redis/redis.conf

# Tell Redis to start using your custom configuration
CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

# Expose the default Redis port
EXPOSE 6379